// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0BLzOGmy0aLUKv4aOmJEdNuyukh0aJJQ',
    appId: '1:498167089645:web:cd5857ba5cf15c7abd7fe4',
    messagingSenderId: '498167089645',
    projectId: 'hamouda-developments',
    authDomain: 'hamouda-developments.firebaseapp.com',
    storageBucket: 'hamouda-developments.firebasestorage.app',
    measurementId: 'G-TDC7S788KY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO3Jyuxgnw-awOVuW1b9A0WwR7W5X6sN4',
    appId: '1:498167089645:android:c8bd24d4b1be5c57bd7fe4',
    messagingSenderId: '498167089645',
    projectId: 'hamouda-developments',
    storageBucket: 'hamouda-developments.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB6MMgjOAOluuRVam-igQjcX9uYUYkO1A',
    appId: '1:498167089645:ios:fd0535759daff7d8bd7fe4',
    messagingSenderId: '498167089645',
    projectId: 'hamouda-developments',
    storageBucket: 'hamouda-developments.firebasestorage.app',
    iosBundleId: 'com.example.hamoudaDevelopments',
  );
}
